config/routes.rb
Sibjob::Application.routes.draw do
  devise_for :parents

  devise_for :siblings

  resources :job_records
  resources :jobs

  resources :parents

  authenticate :sibling do
    resources :siblings do
      member do
        get :jobs
      end
    end
  end

  get "pages/home"

  get "pages/contact"

  match '/contact', :to => 'pages#contact'

  root :to => "pages#home"
end

app/models/sibling.rb
# == Schema Information
# Schema version: 20110514224259
#
# Table name: siblings
#
#  id                     :integer(4)      not null, primary key
#  email                  :string(255)     default(""), not null
#  encrypted_password     :string(128)     default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer(4)      default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#

class Sibling < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :registerable, :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :job
  has_many :job_records, :foreign_key => "performer_id"
  has_many :job_records, :foreign_key => "inspector_id"

  def job_list(performed_on_date = nil)
    performed_on_date ||= Date.today
    Job.to_do_for_sibling(self, performed_on_date)
  end

  def perform_job!(job, performed_on_date = nil)
    performed_on_date ||= Date.today
    job.job_records.build(:performer_id => self.id, :performed_on => performed_on_date)
    job.save!
  end

  def remove_job!(job_record)
    job_record.destroy
  end

  def inspect_job!(job_record)
    job_record.inspect!(self)
  end

  def display_name
    email.partition("@")[0].capitalize
  end

end

app/controllers/siblings_controller.rb
class SiblingsController < ApplicationController
  def index
    redirect_to jobs_sibling_path(current_sibling)
  end

  def jobs
    @sibling = Sibling.find(params[:id])
    @jobs_for_date = date_for_job_list(params)
    @jobs_to_do = Job.to_do_for_sibling(@sibling, @jobs_for_date)
    @jobs_to_do.each do |job|
      job.interval ||= "one-time"
    end
    @job_intervals = @jobs_to_do.group_by {|job| job.interval}
    @job_records_done = JobRecord.done_for_sibling(@sibling, @jobs_for_date)
    @job_records_to_inspect = JobRecord.inspectable_for_sibling(@sibling, @jobs_for_date)
  end

  private

  def date_for_job_list(params)
    date = Date.parse(params[:jobs_on_date]) unless params[:jobs_on_date].nil?
    date ||= build_date_from_params("performed_on", params[:JobRecord]) unless params[:JobRecord].nil?
    date ||= Date.today
    return date
  end
end

app/views/siblings/jobs.html.erb
<div class="main">
  <h1><%= @sibling.email %></h1>
  <%= form_tag(jobs_sibling_path(@sibling), :method => "get") do %>
    Jobs for: <%= date_select("JobRecord", "performed_on", :default => @jobs_for_date) %>
      <%= submit_tag("Go") %>
  <% end %>
  <% unless @job_records_to_inspect.empty? %>
    <h2>Inspections Needed</h2>
    <table class="inspections" summary="Jobs to inspect">
      <% @job_records_to_inspect.each do |job_record| %>
        <tr>
          <td class="job">
            <span class="summary">
              <%= link_to job_record.job.summary, job_path(job_record.job) %>
              <%= "(#{job_record.performer.display_name})" %>
            </span>
          </td>
          <td class="job">
              <%= form_for job_record,
                           :html => { :method => :put } do |f| %>
                <% inspect_label = job_record.inspected? ? "Take Back" : "It's Good!" %>
                <div class="actions"><%= f.submit inspect_label %></div>
              <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  <% end %>
  <% unless @jobs_to_do.empty? %>
    <% @job_intervals.keys.sort.each do |interval| %>
        <h2><%= interval.capitalize %> Jobs</h2>
        <table class="jobs" summary="Sibling <%= interval %> jobs">
          <% @job_intervals[interval].each do |job| %>
            <tr>
              <td class="job">
                <span class="summary"><%= link_to job.summary, job_url(job) %></span>
              </td>
              <td class="points">
                <span class="pointvalue"><%= job.pointvalue %></span>
              </td>
              <td>
                <%= form_for job.job_records.
                                          build(:performer_id => @sibling.id,
                                                :performed_on => @jobs_for_date) do |f| %>
                    <div><%= f.hidden_field :job_id %></div>
                    <div><%= f.hidden_field :performed_on %></div>
                    <div class="actions"><%= f.submit "Done!" %></div>
                <% end %>
              </td>
            </tr>
          <% end %>
        </table>
    <% end %>
  <% end %>

  <% unless @job_records_done.empty? %>
      <h2>Completed Jobs</h2>
      <table class="jobs" summary="Sibling performed jobs">
        <% @job_records_done.each do |job_record| %>
          <tr>
            <td class="job">
              <span class="summary">
                <%= link_to job_record.job.summary, job_url(job_record.job.id) %>
                <%= "(Inspection not needed)" unless job_record.job.inspectable %>
              </span>
            </td>
            <td class="points">
              <span class="pointvalue"><%= job_record.job.pointvalue %></span>
            </td>
            <td class="inspection">
              <% unless job_record.inspected? %>
                <%= form_for job_record, :html => { :method => :delete } do |f| %>
                  <div class="actions"><%= f.submit "Undo" %></div>
                <% end %>
              <% else %>
                <span class="inspected">Inspected!</span>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
  <% end %>
</div>