config/routes.rb
Sibjob::Application.routes.draw do
  devise_for :parents

  devise_for :siblings

  resources :job_records
  resources :jobs

  resources :parents

  authenticate :sibling do
    resources :siblings do
      member do
        get :jobs
      end
    end
  end

  get "pages/home"

  get "pages/contact"

  match '/contact', :to => 'pages#contact'

  root :to => "pages#home"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sibjob</title>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
  <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
  <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
  <%= stylesheet_link_tag 'custom', :media => 'screen' %>
</head>
<body>
    <div class="container">
      <header>
        <nav class="round">
          <ul>
            <% if sibling_signed_in? %>
              <li><%= link_to "Today's Jobs", jobs_sibling_path(current_sibling) %></li>
              <li><%= link_to "Sign Out", destroy_sibling_session_path %></li>
            <% else %>
                <li><%= link_to "Sign In", new_sibling_session_path %></li>
            <% end %>
          </ul>
        </nav>
      </header>
      <section class="round">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </section>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>